version: '3.8'
services:
  nodered:
    container_name: node-red-os-iot
    image: osiot/node-red-os-iot:latest
    environment:
      - LOCAL_PORT=${LOCAL_PORT}
      - SERVICE_PORT=${SERVICE_PORT}
    ports:
      - "${LOCAL_PORT}:${SERVICE_PORT}"
    restart: always
    networks:
      - iot_net

networks:
  iot_net:
    external: true