version: '3.8'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${LOCAL_PORT}:${SERVICE_PORT}"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD} # Admin password for Grafana
    networks:
      - iot_net  # Connect this service to the 'iot_net' network
networks:
  iot_net:
    external: true
volumes:
  grafana_data:
